apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker-prd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/leandromrocha/argocd.git'
    path: prd/worker
    targetRevision: master
  destination:
    namespace: vote-prd
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
